---
# tasks file for php
- name: Install PHP extensions
  apt:
    name: "{{ extension }}"
    state: present
  become: yes
  loop: 
    - php-gd
    - php-ssh2
  loop_control:
    loop_var: extension
