---
- name: Update and upgrade packages
  hosts: test_server
  become: yes
  tasks:
    - name: Update package list
      apt:
        update_cache: yes
    - name: Upgrade package
      apt:
        upgrade: yes
