---
# - name: Update
#   hosts: staging
#   become: true

#   tasks:
#     - name: Update and upgrade apt packages
#       apt:
#         upgrade: yes
#         update_cache: yes
#         cache_valid_time: 86400

- name: Install required packages
  hosts: staging  
  become: true 
  tasks:  
    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Ensure Apache is running and enabled
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Install MySQL server
      apt:
        name: 
          - mysql-server
          - python3-mysqldb
        state: present

    - name: Ensure MySQL service is running and enabled
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Install PHP and related modules
      apt:
        name: 
          - php
          - php-mysql
          - libapache2-mod-php
          - php-cli
        state: present

    - name: Restart Apache to apply PHP modules
      service:
        name: apache2
        state: restarted

    - name: Add Google Cloud SDK apt key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add Google Cloud SDK apt repository
      apt_repository:
        repo: "deb http://packages.cloud.google.com/apt cloud-sdk main"
        state: present

    - name: Update apt and install Google Cloud SDK
      apt:
        name: google-cloud-sdk
        state: latest
        update_cache: yes