---
# tasks file for wordpress
- name: Include MySQL role variables
  include_vars:
    file: ../../mysql/defaults/main.yml

- name: Download WordPress
  get_url:
    url: http://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz
    validate_certs: no

- name: Extract WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/
    copy: no
  become: yes

- name: Create a new Apache virtual host configuration for WordPress
  become: yes
  template:
    src: wordpress.conf.j2
    dest: /etc/apache2/sites-available/wordpress.conf
  notify:
    - restart apache

- name: Enable WordPress site
  become: yes
  command: a2ensite wordpress.conf
  notify:
    - restart apache    

- name: Update default Apache site
  become: yes
  lineinfile:
    dest: /etc/apache2/sites-available/000-default.conf
    regexp: "(.)+DocumentRoot /var/www/html"
    line: "DocumentRoot /var/www/wordpress"
  notify:
    - restart apache

- name: Check if wp-config.php exists
  stat:
    path: /var/www/wordpress/wp-config.php
  register: wp_config_exists
  become: yes

- name: Rename WordPress sample config file
  command: mv /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php
  when: not wp_config_exists.stat.exists
  become: yes

- name: Update WordPress config file
  lineinfile:
    dest: /var/www/wordpress/wp-config.php
    regexp: "{{ wp_config_item.regexp }}"
    line: "{{ wp_config_item.line }}"
  loop:
    - { regexp: "define\\( 'DB_NAME', '(.+)' \\);", line: "define( 'DB_NAME', '{{ wp_mysql_db }}' );" }
    - { regexp: "define\\( 'DB_USER', '(.+)' \\);", line: "define( 'DB_USER', '{{ wp_mysql_user }}' );" }
    - { regexp: "define\\( 'DB_PASSWORD', '(.+)' \\);", line: "define( 'DB_PASSWORD', '{{ wp_mysql_password }}' );" }
    - { regexp: "define\\( 'DB_HOST', '(.+)' \\);", line: "define( 'DB_HOST', 'localhost' );" }
  loop_control:
    loop_var: wp_config_item
  become: yes
