---
name: Create staging server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create_staging_srv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      


      - name: Authenticate with GCP
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
        
      - name: Mask generated GCP values
        run: |
          echo "::add-mask::${{ env.CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE }}"
          echo "::add-mask::${{ env.GOOGLE_APPLICATION_CREDENTIALS }}"
          echo "::add-mask::${{ env.GOOGLE_GHA_CREDS_PATH }}"
          echo "::add-mask::${{ env.CLOUDSDK_CORE_PROJECT }}"
          echo "::add-mask::${{ env.CLOUDSDK_PROJECT }}"
          echo "::add-mask::${{ env.GCLOUD_PROJECT }}"
          echo "::add-mask::${{ env.GCP_PROJECT }}"
          echo "::add-mask::${{ env.GOOGLE_CLOUD_PROJECT }}" 

      - name: Terraform Initialize and Apply
        working-directory: ./terraform
        id: terraform
        run: |
          terraform init
          terraform apply -auto-approve
  
  setup_ansible:
    needs: create_staging_srv
    runs-on: ubuntu-latest
    steps:  
    
    - name: Checkout code
      uses: actions/checkout@v4
    


    - name: Authenticate with GCP
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'  
    
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
    
    - name: Mask generated GCP values
      run: |
        echo "::add-mask::${{ env.CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE }}"
        echo "::add-mask::${{ env.GOOGLE_APPLICATION_CREDENTIALS }}"
        echo "::add-mask::${{ env.GOOGLE_GHA_CREDS_PATH }}"
        echo "::add-mask::${{ env.CLOUDSDK_CORE_PROJECT }}"
        echo "::add-mask::${{ env.CLOUDSDK_PROJECT }}"
        echo "::add-mask::${{ env.GCLOUD_PROJECT }}"
        echo "::add-mask::${{ env.GCP_PROJECT }}"
        echo "::add-mask::${{ env.GOOGLE_CLOUD_PROJECT }}" 
    
    - name: Fetch instance details
      id: fetch_instance_details
      run: |
        INSTANCE_NAME=$(gcloud compute instances list --filter="labels.type=staging" --format='value(name)')
        echo "INSTANCE_NAME=$INSTANCE_NAME" >> $GITHUB_ENV
        echo "::add-mask::$INSTANCE_NAME"
    
        INSTANCE_ZONE=$(gcloud compute instances list --filter="labels.type=staging" --format='value(zone)')
        echo "INSTANCE_ZONE=$INSTANCE_ZONE" >> $GITHUB_ENV
        echo "::add-mask::$INSTANCE_ZONE"
    
        INSTANCE_IP=$(gcloud compute instances describe $INSTANCE_NAME --zone $INSTANCE_ZONE --format='value(networkInterfaces[0].accessConfigs[0].natIP)')
        echo "INSTANCE_IP=$INSTANCE_IP" >> $GITHUB_ENV
        echo "::add-mask::$INSTANCE_IP"
    
        INSTANCE_HOSTNAME=$(gcloud compute instances describe $INSTANCE_NAME --zone $INSTANCE_ZONE --format='value(hostname)')
        echo "INSTANCE_HOSTNAME=$INSTANCE_HOSTNAME" >> $GITHUB_ENV
        echo "::add-mask::$INSTANCE_HOSTNAME"
        
        # Set outputs
        echo "instance_name=$INSTANCE_NAME" >> $GITHUB_OUTPUT
        echo "instance_zone=$INSTANCE_ZONE" >> $GITHUB_OUTPUT
        echo "ip=$INSTANCE_IP" >> $GITHUB_OUTPUT
        echo "hostname=$INSTANCE_HOSTNAME" >> $GITHUB_OUTPUT
          
    - name: Update default.yml
      run: |
        HOSTNAME=${{ steps.fetch_instance_details.outputs.hostname }}
        sed -i "s|your_domain|$HOSTNAME|" ./ansible_fredrik/vars/default.yml
      
      

    - name: Display default.yml
      run: |
        cat ./ansible_fredrik/vars/default.yml
    
    - name: Update Inventory File
      run: |
        sed -i "s|PATH_TO_SERVICE_ACCOUNT_FILE|$GOOGLE_GHA_CREDS_PATH|" ./ansible_fredrik/misc/inventory.gcp.yml
        sed -i "s|PROJECT_ID|$GCP_PROJECT|" ./ansible_fredrik/misc/inventory.gcp.yml   
    
    - name: Install dependencies
      run: |
        /opt/pipx/venvs/ansible-core/bin/python -m pip install google-auth requests
       
    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: playbook.yml
        directory: ./ansible_fredrik
        options: |
          --inventory misc/inventory.gcp.yml
          --verbose
          -vvvv
