---
name: Create staging server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create_staging_srv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Authenticate with GCP
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      
      - name: Mask generated GCP values
        run: |
          echo "::add-mask::${{ env.CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE }}"
          echo "::add-mask::${{ env.GOOGLE_APPLICATION_CREDENTIALS }}"
          echo "::add-mask::${{ env.GOOGLE_GHA_CREDS_PATH }}"
          echo "::add-mask::${{ env.CLOUDSDK_CORE_PROJECT }}"
          echo "::add-mask::${{ env.CLOUDSDK_PROJECT }}"
          echo "::add-mask::${{ env.GCLOUD_PROJECT }}"
          echo "::add-mask::${{ env.GCP_PROJECT }}"
          echo "::add-mask::${{ env.GOOGLE_CLOUD_PROJECT }}" 
      
      - name: Terraform Initialize and Apply
        working-directory: ./terraform
        id: terraform
        run: |
          terraform init
          terraform apply -auto-approve
  
  setup_ansible:
    needs: create_staging_srv
    runs-on: ubuntu-latest
    steps:  
    
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Authenticate with GCP
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'  
    
    - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
  
    - name: Fetch instance name and zone
      id: fetch_instance_name
      run: |
        INSTANCE_NAME=$(gcloud compute instances list --filter="labels.type=staging" --format='value(name)')
        echo "::set-output name=instance_name::$INSTANCE_NAME"
        INSTANCE_ZONE=$(gcloud compute instances list --filter="labels.type=staging" --format='value(zone)')
        echo "::set-output name=instance_zone::$INSTANCE_ZONE"
    
        - name: Get instance IP
      id: get_ip
      run: |
        INSTANCE_NAME=${{ steps.fetch_instance_name.outputs.instance_name }}
        INSTANCE_ZONE=${{ steps.fetch_instance_name.outputs.instance_zone }}
        INSTANCE_IP=$(gcloud compute instances describe $INSTANCE_NAME --zone $INSTANCE_ZONE --format='value(networkInterfaces[0].accessConfigs[0].natIP)')
        echo "::set-output name=ip::$INSTANCE_IP"

    - name: Update default.yml
      run: |
        IP=${{ steps.get_ip.outputs.ip }}
        sed -i "s|your_domain|$IP|" ./ansible_fredrik/vars/default.yml 

    - name: Mask generated GCP values
      run: |
        echo "::add-mask::${{ env.CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE }}"
        echo "::add-mask::${{ env.GOOGLE_APPLICATION_CREDENTIALS }}"
        echo "::add-mask::${{ env.GOOGLE_GHA_CREDS_PATH }}"
        echo "::add-mask::${{ env.CLOUDSDK_CORE_PROJECT }}"
        echo "::add-mask::${{ env.CLOUDSDK_PROJECT }}"
        echo "::add-mask::${{ env.GCLOUD_PROJECT }}"
        echo "::add-mask::${{ env.GCP_PROJECT }}"
        echo "::add-mask::${{ env.GOOGLE_CLOUD_PROJECT }}"    

    - name: Update Inventory File
      run: |
        sed -i "s|PATH_TO_SERVICE_ACCOUNT_FILE|$GOOGLE_GHA_CREDS_PATH|" ./ansible_fredrik/misc/inventory.gcp.yml
        sed -i "s|PROJECT_ID|$GCP_PROJECT|" ./ansible_fredrik/misc/inventory.gcp.yml   
    
    - name: Install dependencies
      run: |
        /opt/pipx/venvs/ansible-core/bin/python -m pip install google-auth requests
       
    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: playbook.yml
        directory: ./ansible_fredrik
        options: |
          --inventory misc/inventory.gcp.yml
          --verbose
          -vvvv
