---
name: PHP Linting

on: [pull_request, workflow_dispatch]

jobs:
  phplint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint PHP files
        uses: overtrue/phplint@main
        with:
          path: .
          options: --exclude=vendor
