---
name: PHP Linting

on: [pull_request, workflow_dispatch]

jobs:
  phplint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2.6' # or your desired PHP version
          extensions: mbstring, intl, gd, xml, ctype, zip # Add other extensions if required
          tools: phpcs # This installs PHP CodeSniffer

      - name: Run PHP_CodeSniffer
        run: |
          phpcs --standard=PSR2 . --ignore=vendor/* # Change to your preferred standard and any other options you want
       
