---
name: PHP Linting

on: [pull_request, workflow_dispatch]

jobs:
  phplint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check PHP syntax errors
        uses: overtrue/phplint@6.0.0
            
       
