---
name: PHP Linting

on: [pull_request, workflow_dispatch]

jobs:
  phplint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: PHP Lint
        uses: michaelw90/PHP-Lint@master
       